Update the keyagreement reference
so that the "Update Editor's Copy" GitHub action succeeds.

The GitHub action fails with the following message:
```
/github/home/.cache/xml2rfc/reference.DOI.10.6028_NIST.SP.800-56Ar3--anchor=keyagreement.xml: fetching
*** 404 NOT FOUND while fetching https://xml2rfc.tools.ietf.org/public/rfc/bibxml7/reference.DOI.10.6028/NIST.SP.800-56Ar3.xml?anchor=keyagreement
*** No such file or directory @ rb_sysopen - /github/home/.cache/xml2rfc/reference.DOI.10.6028_NIST.SP.800-56Ar3--anchor=keyagreement.xml for /github/home/.cache/xml2rfc/reference.DOI.10.6028_NIST.SP.800-56Ar3--anchor=keyagreement.xml
Error: Unable to parse the XML document: /dev/stdin
make: *** [lib/main.mk:68: draft-irtf-cfrg-opaque.xml] Error 1
```
See https://github.com/cfrg/draft-irtf-cfrg-opaque/runs/1797781503 .

There is an alternate link to this reference here:
https://xml2rfc.tools.ietf.org/public/rfc/bibxml-nist/reference.NIST.NIST.SP.800-56Ar3.xml .